### ISSUE TITLE
[ATIVIDADE] Interfaces funcionais

### ISSUE THREAD

**Issue by mbnakaya** [mbnakaya/ada-t1002-jv-3#1]
> ⚠️ atividade individual
## Enunciado 📖 
Crie uma aplicação que simule uma calculadora utilizando lambda e a interface funcional BiFunction.
Para isso crie uma classe `Calculadora` com um método chamado `executar(int x, int y, BiFuncition)` que recebe dois números inteiros positivos e uma BiFunction como parâmetros.
Desenvolva a implementação em lambda para cada operação, ou seja: somar, subtrair, multiplicar e dividir (resultado inteiro). Chama a função `executar()` para cada uma das operações.
O método `executar()` deve imprimir na tela (`System.out.println()`) o resultado final das operações que realizar.

## Entrega 📮 
Adicionem um comentário nesta Issue, contendo a classe de resolução. Para facilitar o entendimento, peço que respondam da seguinte forma:
```java
class Calculadora {
    public static void main(String[] args) {
        // lambda para soma
        // lambda para subtracao
        // lambda para multiplicacao
        // lambda para divisao
    }

    public void executar(int x, int y, BiFuncition biFunction) {
        // ...
    }
}
```

## Prazo 📆 
As respontas serão aceitas até o dia 26/09, às 23:59.

**Comment by GustavoRSSBr** [comment]
Gustavo Rodrigues Santos Silva
```java class Caculadora {
	public static void main(String[] args) {

		BiFunction<Integer, Integer, Integer> multiplicar = (a, b) -> a * b;
		BiFunction<Integer, Integer, Integer> somar = (a, b) -> a + b;
		BiFunction<Integer, Integer, Double> dividir = (a, b) -> a / b.doubleValue();
		BiFunction<Integer, Integer, Integer> subtrair = (a, b) -> a - b;

		System.out.print("10 + 10 ");
		executar(10, 10, somar);
		System.out.print("10 - 10 ");
		executar(10, 10, subtrair);
		System.out.print("10 * 10 ");
		executar(10, 10, multiplicar);
		System.out.print("3 / 2 ");
		executar(3, 2, dividir);

	}

	public static <T, U, X> void executar(T t, U u, BiFunction<T, U, X> biFunction) {

		System.out.print(" = " + biFunction.apply(t, u));
		System.out.println();

	}

**Comment by LucasFurlannnn** [comment]
class Calculadora {

    public static void main(String[] args) {
        // lambda para soma
        int soma = (x, y) -> x + y;

        // lambda para subtração
        int subtracao = (x, y) -> x - y;

        // lambda para multiplicação
        int multiplicacao = (x, y) -> x * y;

        // lambda para divisão (resultado inteiro)
        int divisao = (x, y) -> x / y;

        // Chamada da função executar() para cada operação
        executar(10, 20, soma);
        executar(10, 20, subtracao);
        executar(10, 20, multiplicacao);
        executar(10, 20, divisao);
    }

    public void executar(int x, int y, BiFunction biFunction) {
        // Imprime na tela o resultado da operação
        System.out.println(biFunction.apply(x, y));
    }
}

**Comment by PedroQueiroz1** [comment]
// Pedro Henrique Queiroz
public class Calculadora {
    public static final String SOMA = "[SOMA] ";
    public static final String SUBTRACAO = "[SUBTRAÇÃO] ";
    public static final String MULTIPLICACAO = "[MULTIPLICAÇÃO] ";
    public static final String DIVISAO = "[DIVISÃO] ";
    public static final String RESULTADO = "O resultado da operação entre %s e %s é: ";
    public static final String ERRO = "Deu ruim :( \n";

    public static void main(String[] args) {
        int numero1 = 5;
        int numero2 = 0;
        int numero3 = 1;

        executar(numero1, numero2, (x, y) -> SOMA + (x + y)); // lambda para soma
        executar(numero1, numero2, (x, y) -> SUBTRACAO + (x - y)); // lambda para subtracao
        executar(numero1, numero2, (x,y) -> MULTIPLICACAO + (x * y)); // lambda para multiplicacao
        executar(numero1, numero2, (x, y) -> DIVISAO + (x / y)); // lambda para divisao por 0
        executar(numero1, numero3, (x, y) -> DIVISAO + (x / y)); // lambda para divisao
    }

    public static void executar(int x, int y, BiFunction<Integer, Integer, String> biFunction) {
        try {
            String resultado = String.format(RESULTADO, x, y);
            System.out.println(resultado + biFunction.apply(x, y) + "\n");
        } catch (ArithmeticException e) {
            System.out.println(ERRO);
        }
    }
}

**Comment by GabrielZappe** [comment]
import java.util.Scanner;
import java.util.function.BiFunction;

public class Calculadora {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.print("Digite o primeiro número: ");
        int numero1 = scanner.nextInt();
        
        System.out.print("Digite o segundo número: ");
        int numero2 = scanner.nextInt();
        
        System.out.print("Digite o terceiro número: ");
        int numero3 = scanner.nextInt();

        Operacao[] operacoes = {
            new Operacao("SOMA", (x, y) -> x + y),
            new Operacao("SUBTRACAO", (x, y) -> x - y),
            new Operacao("MULTIPLICACAO", (x, y) -> x * y),
            new Operacao("DIVISAO", (x, y) -> x / y)
        };

        for (Operacao operacao : operacoes) {
            System.out.print(operacao.getNome() + ": ");
            executar(numero1, numero2, operacao.getOperacao());
        }

        System.out.print("DIVISAO por " + numero3 + ": ");
        executar(numero1, numero3, (x, y) -> x / y);
        
        scanner.close();
    }

    public static void executar(int x, int y, BiFunction<Integer, Integer, Integer> operacao) {
        try {
            int resultado = operacao.apply(x, y);
            System.out.println("Resultado: " + resultado);
        } catch (ArithmeticException e) {
            System.out.println("Erro: Divisão por zero");
        }
    }

    static class Operacao {
        private String nome;
        private BiFunction<Integer, Integer, Integer> operacao;

        public Operacao(String nome, BiFunction<Integer, Integer, Integer> operacao) {
            this.nome = nome;
            this.operacao = operacao;
        }

        public String getNome() {
            return nome;
        }

        public BiFunction<Integer, Integer, Integer> getOperacao() {
            return operacao;
        }
    }
}

**Comment by Lucasziem** [comment]
//Lucas Antonio Baron Ziembowicz

```
import java.util.function.BiFunction;

class Calculadora {
    public static void main(String[] args) {
        Calculadora calculadora = new Calculadora();

        // Lambda para soma
        calculadora.executar(5, 3, (x, y) -> x + y);

        // Lambda para subtracao
        calculadora.executar(8, 2, (x, y) -> x - y);

        // Lambda para multiplicacao
        calculadora.executar(4, 6, (x, y) -> x * y);

        // Lambda para divisao (resultado inteiro)
        calculadora.executar(10, 2, (x, y) -> x / y);
    }

    public void executar(int x, int y, BiFunction<Integer, Integer, Integer> biFunction) {
        int resultado = biFunction.apply(x, y);
        System.out.println("Resultado: " + resultado);
    }
}
```

**Comment by DouglasD18** [comment]
Douglas Aguiar Alcântara

```
import java.util.function.BiFunction;

class Calculadora {
  public static void main(String[] args) {
    // lambda para soma
    BiFunction<Integer, Integer, Integer> sum = Integer::sum;

    // lambda para subtracao
    BiFunction<Integer, Integer, Integer> sub = (a, b) -> a - b;

    // lambda para multiplicacao
    BiFunction<Integer, Integer, Integer> mul = (a, b) -> a * b;

    // lambda para divisao
    BiFunction<Integer, Integer, Double> div = (a, b) -> a.doubleValue() / b.doubleValue();

    System.out.print("Somando 18 com 9. ");
    executar(18, 9, sum);

    System.out.print("Subtraindo 21 de 88. ");
    executar(88, 21, sub);

    System.out.print("Multiplicando 3 com 8. ");
    executar(3, 8, mul);

    System.out.print("Divindo 27 por 5. ");
    executar(27, 5, div);
  }

  public static <T, G> void executar(T x, T y, BiFunction<T, T, G> biFunction) {
    System.out.println("Resultado: " + biFunction.apply(x, y));
  }
}
```

**Comment by Guisaber** [comment]
Guilherme Bernardes

class Calculadora {
    public static void main(String[] args) {
        Calculadora calculadora = new Calculadora();

        // Lambda para adição
        calculadora.executar(3, 8, (a, b) -> a + b);

        // Lambda para subtração
        calculadora.executar(10, 5, (a, b) -> a - b);

        // Lambda para multiplicação
        calculadora.executar(5, 12, (a, b) -> a * b);

        // Lambda para divisão 
        calculadora.executar(144,12, (a, b) -> a/ b);
    }

    public void executar(int a, int b, BiFunction<Integer, Integer, Integer> biFunction) {
        int result = biFunction.apply(a, b);
        System.out.println("Resultado é:  " + result);
    }

**Comment by Sustavo** [comment]
import java.util.function.BiFunction;

public class Main {
    public static void main(String[] args) {
        System.out.println("Results: ");

        executar(10, 10, '+');
        executar(10, 10, '-');
        executar(10, 10, '*');
        executar(10, 10, '/');

    }

    public static <T, U, X> void executar(T t, U u, char operacao) {
        BiFunction<Integer, Integer, Integer> operacaoAritmetica = null;
        switch (operacao) {
            case '*': operacaoAritmetica = (a, b) -> a * b; break;
            case '+': operacaoAritmetica = (a, b) -> a + b; break;
            case '/': operacaoAritmetica = (a, b) -> a / b; break;
            case '-': operacaoAritmetica = (a, b) -> a - b; break;
            default:
                System.out.println("Operação inválida");
                return;
        }
        System.out.println(t.toString() + " " + operacao + " " + u.toString() + " = " + operacaoAritmetica.apply((Integer)t, (Integer)u));
    }
}

**Comment by BrunoSDMDev** [comment]
<Strong>  Bruno Silva de Morais </Strong>

```java
import java.util.Scanner;
import java.util.function.BiFunction;

public class Calculadora {
    public static final String Soma = "";
    public static final String Subtracao = "";
    public static final String Multiplicacao = "";
    public static final String Divisao = "";
    public static final String Resultado = "Resultado: ";

    public static void main(String[] args) {
        Calculadora calculadora = new Calculadora();
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite o primeiro número:");
        double primeiroNumero = scanner.nextInt();

        System.out.println("Digite o segundo número:");
         double segundoNumero = scanner.nextInt();

        System.out.println("Digite o número correspondente à operação desejada" + "\n" +
                "1 ➞ Soma" + "\n" +
                "2 ➞ Subtração" + "\n" +
                "3 ➞ Multiplicação" + "\n" +
                "4 ➞ Divisão");

        int operacao = scanner.nextInt();

        switch (operacao) {
            case 1:
                calculadora.executar(primeiroNumero, segundoNumero, (x, y) -> Soma + (x + y));
                break;
            case 2:
                calculadora.executar(primeiroNumero, segundoNumero, (x, y) -> Subtracao + (x - y));
                break;
            case 3:
                calculadora.executar(primeiroNumero, segundoNumero, (x,y) -> Multiplicacao + (x * y));
                break;
            case 4:
                calculadora.executar(primeiroNumero, segundoNumero, (x, y) -> Divisao + (x / y));
                break;
            default:
                System.out.println("Operação inválida.");
                break;
        }

        scanner.close();
    }

    public void executar(double x, double y, BiFunction<Double, Double, String> operacao) {
        String resultado = String.format(Resultado, x, y);
        System.out.println(resultado + operacao.apply(x, y) + "\n");
    }
}
```

**Comment by Souzamanda** [comment]
Amanda Cordeiro de Souza Puttomatti
```java
import java.util.function.BiFunction;

public class Calculadora {
    public static void main(String[] args) {

        // lambda para soma
        executar(2, 5, (x,y) -> x + y);

        // lambda para subtracao
        executar(2, 5, (x,y) -> x - y);

        // lambda para multiplicacao
        executar(2, 5, (x,y) -> x * y);

        // lambda para divisao
        executar(2, 0, (x,y) -> x.doubleValue() / y.doubleValue());
    }

    public static <T> void executar(int x, int y, BiFunction<Integer, Integer, T> biFunction) {
        try {
            System.out.println(biFunction.apply(x, y));
        } catch (ArithmeticException err) {
            System.out.println("Erro: Divisor não pode ser 0");
        }

    }
}
```

**Comment by Souzamanda** [comment]
Amanda Cordeiro de Souza Puttomatti
```java
import java.util.function.BiFunction;

public class Calculadora {
    public static void main(String[] args) {

        // lambda para soma
        executar(2, 5, (x,y) -> x + y);

        // lambda para subtracao
        executar(2, 5, (x,y) -> x - y);

        // lambda para multiplicacao
        executar(2, 5, (x,y) -> x * y);

        // lambda para divisao
        executar(2, 0, (x,y) -> {
            if (y != 0) {
                return x.doubleValue() / y.doubleValue();
            } else {
                return "Erro: Divisor não pode ser 0.";
            }
        });
    }

    public static <T> void executar(int x, int y, BiFunction<Integer, Integer, T> biFunction) {
        System.out.println(biFunction.apply(x, y));
    }
}
```

**Comment by Alleoni** [comment]
```java
import java.util.function.BiFunction;

public class Main {
    public static void main(String[] args) {

        // lambda para multiplicacao
        BiFunction<Integer, Integer, Integer> multiplicar = (x, y) -> x * y;
        // lambda para divisao
        BiFunction<Integer, Integer, Integer> dividir = (x, y) -> x / y;
        // lambda para soma
        BiFunction<Integer, Integer, Integer> somar = (x, y) -> x + y;
        // lambda para subtracao
        BiFunction<Integer, Integer, Integer> subtrair = (x, y) -> x - y;

        executar(10,5, multiplicar);

        executar(10,5, dividir);

        executar(10,5, somar);

        executar(10,5, subtrair);


        }
        public static void executar(Integer x, Integer y, BiFunction<Integer, Integer, Integer>biFunction){
        Integer resultado = biFunction.apply(x,y);
            System.out.println("Resultado: " + resultado);
    }
}
```

**Comment by jpastolfo** [comment]
```java
import java.util.function.BiFunction;

class Claculadora {
    public static void main(String[] args) {
        int numero0 = 10;
        int numero1 = 7;

        // lambda para soma
        executar(numero0,numero1,(x,y) -> String.valueOf(x + y));
        // lambda para subtracao
        executar(numero0,numero1,(x,y) -> String.valueOf(x-y));
        // lambda para multiplicacao
        executar(numero0,numero1,(x,y) -> String.valueOf(x*y));
        // lambda para divisao
        executar(numero0,numero1,(x,y) -> String.valueOf(x.doubleValue()/y.doubleValue()));
    }

    public static void executar(int x, int y, BiFunction<Integer,Integer,String> biFunction) {
        try {
            System.out.println(biFunction.apply(x,y));
        } catch (RuntimeException e) {
            System.out.println("Input error!");
        }
    }
}

```

**Comment by victorscarsi** [comment]
import java.util.function.BiFunction;

class Calculadora {
	public static void main(String[] args) {
		BiFunction<Integer, Integer, Integer> soma = (a, b) -> a + b;
		BiFunction<Integer, Integer, Integer> subtracao = (a, b) -> a - b;
        BiFunction<Integer, Integer, Integer> multiplicacao = (a, b) -> a * b;
        BiFunction<Integer, Integer, Double> divisao = (a, b) -> (double) a / b;

        int num1 = 5;
        int num2 = 3;

		System.out.print(num1 + " + " + num2 + " = "); 
		executar(num1, num2, soma);
		System.out.print(num1 + " - " + num2 + " = "); 
		executar(num1, num2, subtracao);
		System.out.print(num1 + " x " + num2 + " = "); 
		executar(num1, num2, multiplicacao);
		System.out.print(num1 + " / " + num2 + " = "); 
		executar(num1, num2, divisao);
	}

	public static <T, U> void executar(T x, T y, BiFunction<T, T, U> biFunction) {
		System.out.println(biFunction.apply(x, y));
	} 
}
